version: '3.8'

services:
  mc_user:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_NAME=kittydelivery
      - DB_ID_NAME=postgres
      - DB_ID_PASSWORD=admin
      - DB_HOST=postgres
      - DB_DIALECT=postgres
      - ALLOWED_ORIGIN=https://localhost:8080
      - ALLOWED_REFERER=https://localhost:3000/api
    networks:
      - shared-net

networks:
  shared-net:
    external: true
